id: alba-public
name: "Alba Public Library and Museum"
vendor: apollo
region: Wood County
catalogUrl: https://alba.biblionix.com
enabled: true

branches:
  - id: "alba-public:main"
    name: "Alba Public Library and Museum"
    code: main
    city: Alba

adapters:
  - protocol: apollo_api
    baseUrl: https://alba.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
