id: bay-city-public
name: Bay City Public Library
vendor: atriuum
region: Matagorda County
catalogUrl: https://baycitytxlib.booksys.net/opac/baycity/
enabled: true

branches:
  - id: "bay-city-public:main"
    name: Bay City Public Library
    code: baycity
    city: Bay City
  - id: "bay-city-public:sargent"
    name: Sargent Branch Library
    code: sargent
    city: Sargent

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://baycitytxlib.booksys.net/opac/baycity
    timeoutMs: 15000
    maxConcurrency: 2
