id: buffalo-public
name: Buffalo Public Library
vendor: atriuum
region: Leon County
catalogUrl: https://buffalotexlib.booksys.net/opac/buffalo/
enabled: true

branches:
  - id: "buffalo-public:main"
    name: Buffalo Public Library
    code: main
    city: Buffalo

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://buffalotexlib.booksys.net/opac/buffalo
    timeoutMs: 15000
    maxConcurrency: 2
