id: comanche-public
name: "Comanche Public Library"
vendor: apollo
region: Comanche County
catalogUrl: https://comanche.biblionix.com
enabled: true

branches:
  - id: "comanche-public:main"
    name: "Comanche Public Library"
    code: main
    city: Comanche

adapters:
  - protocol: apollo_api
    baseUrl: https://comanche.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
