id: converse-public
name: "Converse Public Library"
vendor: apollo
region: Bexar County
catalogUrl: https://converse.biblionix.com
enabled: true

branches:
  - id: "converse-public:main"
    name: "Converse Public Library"
    code: main
    city: Converse

adapters:
  - protocol: apollo_api
    baseUrl: https://converse.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
