id: corsicana-public
name: Corsicana Public Library
vendor: atriuum
region: Navarro County
catalogUrl: https://corsicanatx.booksys.net/opac/corsicanatx/
enabled: true

branches:
  - id: "corsicana-public:main"
    name: Corsicana Public Library
    code: corsicanatx
    city: Corsicana

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://corsicanatx.booksys.net/opac/corsicanatx
    timeoutMs: 15000
    maxConcurrency: 2
