id: dallas-public
name: Dallas Public Library
vendor: polaris
region: Dallas County
catalogUrl: https://catalog.dallaslibrary.org/polaris/
enabled: false

branches:
  - id: "dallas-public:central"
    name: J. Erik Jonsson Central Library
    code: central
    city: Dallas

adapters:
  - protocol: polaris_papi
    baseUrl: https://catalog.dallaslibrary.org
    timeoutMs: 10000
    maxConcurrency: 2
