id: deleon-public
name: "De Leon City-County Library"
vendor: apollo
region: Comanche County
catalogUrl: https://deleon.biblionix.com
enabled: true

branches:
  - id: "deleon-public:main"
    name: "De Leon City-County Library"
    code: main
    city: De Leon

adapters:
  - protocol: apollo_api
    baseUrl: https://deleon.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
