id: dickinson-public
name: "Dickinson Public Library"
vendor: apollo
region: Galveston County
catalogUrl: https://dickinson.biblionix.com
enabled: true

branches:
  - id: "dickinson-public:main"
    name: "Dickinson Public Library"
    code: main
    city: Dickinson

adapters:
  - protocol: apollo_api
    baseUrl: https://dickinson.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
