id: dublin-public
name: "Dublin Public Library"
vendor: apollo
region: Erath County
catalogUrl: https://dublin.biblionix.com
enabled: true

branches:
  - id: "dublin-public:main"
    name: "Dublin Public Library"
    code: main
    city: Dublin

adapters:
  - protocol: apollo_api
    baseUrl: https://dublin.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
