id: duncanville-public
name: Duncanville Public Library
vendor: koha
region: Dallas County
catalogUrl: https://duncanville.bywatersolutions.com/
enabled: false  # Koha/ByWater blocked by Cloudflare WAF (Best Southwest consortium)

branches:
  - id: "duncanville-public:main"
    name: Duncanville Public Library
    code: main
    city: Duncanville

adapters:
  - protocol: aspen_discovery_api
    baseUrl: https://duncanville.bywatersolutions.com
    timeoutMs: 15000
    maxConcurrency: 2
