id: eden-public
name: "Eden Public Library"
vendor: apollo
region: Concho County
catalogUrl: https://eden.biblionix.com
enabled: true

branches:
  - id: "eden-public:main"
    name: "Eden Public Library"
    code: main
    city: Eden

adapters:
  - protocol: apollo_api
    baseUrl: https://eden.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
