id: ennis-public
name: Ennis Public Library
vendor: atriuum
region: Ellis County
catalogUrl: https://ennis.booksys.net/opac/epl/
enabled: true

branches:
  - id: "ennis-public:main"
    name: Ennis Public Library
    code: main
    city: Ennis

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://ennis.booksys.net/opac/epl
    timeoutMs: 15000
    maxConcurrency: 2
