id: flower-mound-public
name: Flower Mound Public Library
vendor: koha
region: Denton County
catalogUrl: https://flowermound.aspendiscovery.org/
enabled: false  # Aspen Discovery front-end blocked by Cloudflare WAF

branches:
  - id: "flower-mound-public:main"
    name: Flower Mound Public Library
    code: main
    city: Flower Mound

adapters:
  - protocol: aspen_discovery_api
    baseUrl: https://flowermound.aspendiscovery.org
    timeoutMs: 15000
    maxConcurrency: 2
