id: floyd-county
name: "Floyd County Memorial Library"
vendor: apollo
region: Floyd County
catalogUrl: https://floyd.biblionix.com
enabled: true

branches:
  - id: "floyd-county:main"
    name: "Floyd County Memorial Library"
    code: main
    city: Floydada

adapters:
  - protocol: apollo_api
    baseUrl: https://floyd.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
