id: groveton-public
name: Ethel Reese Library (Groveton)
vendor: atriuum
region: Trinity County
catalogUrl: https://grovetontx.booksys.net/opac/grovetontx/
enabled: true

branches:
  - id: "groveton-public:main"
    name: Ethel Reese Library
    code: main
    city: Groveton

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://grovetontx.booksys.net/opac/grovetontx
    timeoutMs: 15000
    maxConcurrency: 2
