id: hemphill-public
name: "Mae S. Bruce Public Library"
vendor: apollo
region: Sabine County
catalogUrl: https://maesbruce.biblionix.com
enabled: true

branches:
  - id: "hemphill-public:main"
    name: "Mae S. Bruce Public Library"
    code: main
    city: Hemphill

adapters:
  - protocol: apollo_api
    baseUrl: https://maesbruce.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
