id: huntsville-public
name: Huntsville Public Library
vendor: koha
region: Walker County
catalogUrl: https://huntsville.aspendiscovery.org/
enabled: false  # Aspen Discovery front-end blocked by Cloudflare WAF

branches:
  - id: "huntsville-public:main"
    name: Huntsville Public Library
    code: main
    city: Huntsville

adapters:
  - protocol: aspen_discovery_api
    baseUrl: https://huntsville.aspendiscovery.org
    timeoutMs: 15000
    maxConcurrency: 2
