id: imperial-public
name: Imperial Public Library
vendor: atriuum
region: Pecos County
catalogUrl: https://imperiallibtx.booksys.net/opac/ipltx/
enabled: true

branches:
  - id: "imperial-public:main"
    name: Imperial Public Library
    code: main
    city: Imperial

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://imperiallibtx.booksys.net/opac/ipltx
    timeoutMs: 15000
    maxConcurrency: 2
