id: jeff-davis-county
name: "Jeff Davis County Library"
vendor: apollo
region: Jeff Davis County
catalogUrl: https://jeffdaviscounty.biblionix.com
enabled: true

branches:
  - id: "jeff-davis-county:main"
    name: "Jeff Davis County Library"
    code: main
    city: Fort Davis

adapters:
  - protocol: apollo_api
    baseUrl: https://jeffdaviscounty.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
