id: kendalia-public
name: Kendalia Public Library
vendor: apollo
region: Kendall County
catalogUrl: https://kendalia.biblionix.com
enabled: true

branches:
  - id: "kendalia-public:main"
    name: Kendalia Public Library
    code: main
    city: Kendalia

adapters:
  - protocol: apollo_api
    baseUrl: https://kendalia.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
