id: krum-public
name: "Krum Public Library"
vendor: apollo
region: Denton County
catalogUrl: https://krum.biblionix.com
enabled: true

branches:
  - id: "krum-public:main"
    name: "Krum Public Library"
    code: main
    city: Krum

adapters:
  - protocol: apollo_api
    baseUrl: https://krum.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
