id: kyle-public
name: "Kyle Public Library"
vendor: apollo
region: Hays County
catalogUrl: https://kyle.biblionix.com
enabled: true

branches:
  - id: "kyle-public:main"
    name: "Kyle Public Library"
    code: main
    city: Kyle

adapters:
  - protocol: apollo_api
    baseUrl: https://kyle.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
