id: league-city
name: Helen Hall Library
vendor: sirsi_dynix
region: Galveston County
catalogUrl: https://hhal.ent.sirsi.net/client/en_US/default
enabled: true

branches:
  - id: "league-city:helen-hall"
    name: Helen Hall Library
    code: helen-hall
    city: League City

adapters:
  - protocol: sirsi_enterprise_scrape
    baseUrl: https://hhal.ent.sirsi.net
    timeoutMs: 10000
    maxConcurrency: 2
