id: madison-county
name: "Madison County Library"
vendor: apollo
region: Madison County
catalogUrl: https://madison.biblionix.com
enabled: true

branches:
  - id: "madison-county:main"
    name: "Madison County Library"
    code: main
    city: Madisonville

adapters:
  - protocol: apollo_api
    baseUrl: https://madison.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
