id: mason-county-public
name: "Mason County Public Library"
vendor: apollo
region: Mason County
catalogUrl: https://masoncounty.biblionix.com
enabled: true

branches:
  - id: "mason-county-public:main"
    name: "Mason County Public Library"
    code: main
    city: Mason

adapters:
  - protocol: apollo_api
    baseUrl: https://masoncounty.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
