id: mathis-public
name: "Mathis Public Library"
vendor: apollo
region: San Patricio County
catalogUrl: https://mathis.biblionix.com
enabled: true

branches:
  - id: "mathis-public:main"
    name: "Mathis Public Library"
    code: main
    city: Mathis

adapters:
  - protocol: apollo_api
    baseUrl: https://mathis.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
