id: menard-public
name: "Menard Public Library"
vendor: apollo
region: Menard County
catalogUrl: https://menard.biblionix.com
enabled: true

branches:
  - id: "menard-public:main"
    name: "Menard Public Library"
    code: main
    city: Menard

adapters:
  - protocol: apollo_api
    baseUrl: https://menard.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
