id: north-richland-hills-public
name: North Richland Hills Public Library
vendor: koha
region: Tarrant County
catalogUrl: https://nrhtx.bywatersolutions.com/
enabled: false  # Koha/ByWater blocked by Cloudflare WAF

branches:
  - id: "north-richland-hills-public:main"
    name: North Richland Hills Public Library
    code: main
    city: North Richland Hills

adapters:
  - protocol: aspen_discovery_api
    baseUrl: https://nrhtx.bywatersolutions.com
    timeoutMs: 15000
    maxConcurrency: 2
