id: paris-public
name: Paris Public Library
vendor: atriuum
region: Lamar County
catalogUrl: https://parispltx.booksys.net/opac/ppl/
enabled: true

branches:
  - id: "paris-public:main"
    name: Paris Public Library
    code: main
    city: Paris

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://parispltx.booksys.net/opac/ppl
    timeoutMs: 15000
    maxConcurrency: 2
