id: quitman-public
name: "Quitman Public Library"
vendor: apollo
region: Wood County
catalogUrl: https://quitman.biblionix.com
enabled: true

branches:
  - id: "quitman-public:main"
    name: "Quitman Public Library"
    code: main
    city: Quitman

adapters:
  - protocol: apollo_api
    baseUrl: https://quitman.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
