id: reagan-county
name: "Reagan County Library"
vendor: apollo
region: Reagan County
catalogUrl: https://reagan.biblionix.com
enabled: true

branches:
  - id: "reagan-county:main"
    name: "Reagan County Library"
    code: main
    city: Big Lake

adapters:
  - protocol: apollo_api
    baseUrl: https://reagan.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
