id: sachse-public
name: Sachse Public Library
vendor: atriuum
region: Dallas County
catalogUrl: https://sachsetx.booksys.net/opac/sachse/
enabled: true

branches:
  - id: "sachse-public:main"
    name: Sachse Public Library
    code: sachse
    city: Sachse

adapters:
  - protocol: atriuum_scrape
    baseUrl: https://sachsetx.booksys.net/opac/sachse
    timeoutMs: 15000
    maxConcurrency: 2
