id: san-benito-public
name: "San Benito Public Library"
vendor: apollo
region: Cameron County
catalogUrl: https://sanbenito.biblionix.com
enabled: true

branches:
  - id: "san-benito-public:main"
    name: "San Benito Public Library"
    code: main
    city: San Benito

adapters:
  - protocol: apollo_api
    baseUrl: https://sanbenito.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
