id: schulenburg-public
name: "Schulenburg Public Library"
vendor: apollo
region: Fayette County
catalogUrl: https://schulenburg.biblionix.com
enabled: true

branches:
  - id: "schulenburg-public:main"
    name: "Schulenburg Public Library"
    code: main
    city: Schulenburg

adapters:
  - protocol: apollo_api
    baseUrl: https://schulenburg.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
