id: seguin-public
name: "Seguin Public Library"
vendor: apollo
region: Guadalupe County
catalogUrl: https://seguin.biblionix.com
enabled: true

branches:
  - id: "seguin-public:main"
    name: "Seguin Public Library"
    code: main
    city: Seguin

adapters:
  - protocol: apollo_api
    baseUrl: https://seguin.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
