id: shackelford-county
name: "Shackelford County Library"
vendor: apollo
region: Shackelford County
catalogUrl: https://shackelford.biblionix.com
enabled: true

branches:
  - id: "shackelford-county:main"
    name: "Shackelford County Library"
    code: main
    city: Albany

adapters:
  - protocol: apollo_api
    baseUrl: https://shackelford.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
