id: temple-public
name: Temple Public Library
vendor: apollo
region: Bell County
catalogUrl: https://templelibrary.biblionix.com
enabled: true

branches:
  - id: "temple-public:main"
    name: Temple Public Library
    code: main
    city: Temple

adapters:
  - protocol: apollo_api
    baseUrl: https://templelibrary.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
