id: upshur-county
name: "Upshur County Library"
vendor: apollo
region: Upshur County
catalogUrl: https://upshur.biblionix.com
enabled: true

branches:
  - id: "upshur-county:main"
    name: "Upshur County Library"
    code: main
    city: Gilmer

adapters:
  - protocol: apollo_api
    baseUrl: https://upshur.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
