id: ward-county
name: "Ward County Public Library"
vendor: apollo
region: Ward County
catalogUrl: https://ward.biblionix.com
enabled: true

branches:
  - id: "ward-county:main"
    name: "Ward County Public Library"
    code: main
    city: Monahans

adapters:
  - protocol: apollo_api
    baseUrl: https://ward.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
