id: wells-branch-public
name: "Wells Branch Community Library"
vendor: apollo
region: Travis County
catalogUrl: https://wellsbranch.biblionix.com
enabled: true

branches:
  - id: "wells-branch-public:main"
    name: "Wells Branch Community Library"
    code: main
    city: Austin

adapters:
  - protocol: apollo_api
    baseUrl: https://wellsbranch.biblionix.com
    timeoutMs: 10000
    maxConcurrency: 2
